//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAdmin.Rbac.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RbacCulture {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RbacCulture() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorAdmin.Rbac.Resources.RbacCulture", typeof(RbacCulture).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string MenuPage_AddButtonText {
            get {
                return ResourceManager.GetString("MenuPage_AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string MenuPage_CancelButtonText {
            get {
                return ResourceManager.GetString("MenuPage_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理选中 的本地化字符串。
        /// </summary>
        public static string MenuPage_ClearBtnText {
            get {
                return ResourceManager.GetString("MenuPage_ClearBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string MenuPage_DeleteButtonText {
            get {
                return ResourceManager.GetString("MenuPage_DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单图标 的本地化字符串。
        /// </summary>
        public static string MenuPage_IconSelectLabel {
            get {
                return ResourceManager.GetString("MenuPage_IconSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元素标识 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuIdentityLabel {
            get {
                return ResourceManager.GetString("MenuPage_MenuIdentityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入页面元素标识 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuIdentityPlaceHolder {
            get {
                return ResourceManager.GetString("MenuPage_MenuIdentityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuNameLablel {
            get {
                return ResourceManager.GetString("MenuPage_MenuNameLablel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入名称 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuNamePlaceHolder {
            get {
                return ResourceManager.GetString("MenuPage_MenuNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuRouteLabel {
            get {
                return ResourceManager.GetString("MenuPage_MenuRouteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入路由 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuRoutePlaceHolder {
            get {
                return ResourceManager.GetString("MenuPage_MenuRoutePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuTypeRadioLabel {
            get {
                return ResourceManager.GetString("MenuPage_MenuTypeRadioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuTypeRadioText1 {
            get {
                return ResourceManager.GetString("MenuPage_MenuTypeRadioText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面元素 的本地化字符串。
        /// </summary>
        public static string MenuPage_MenuTypeRadioText2 {
            get {
                return ResourceManager.GetString("MenuPage_MenuTypeRadioText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入关键字 的本地化字符串。
        /// </summary>
        public static string MenuPage_SearchIconPlaceholder {
            get {
                return ResourceManager.GetString("MenuPage_SearchIconPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string MenuPage_SubmitButtonText {
            get {
                return ResourceManager.GetString("MenuPage_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string MenuPage_Title {
            get {
                return ResourceManager.GetString("MenuPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级菜单 的本地化字符串。
        /// </summary>
        public static string MenuPage_UpMenuSelectTitle {
            get {
                return ResourceManager.GetString("MenuPage_UpMenuSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级菜单选择 的本地化字符串。
        /// </summary>
        public static string MenuPage_UpMenuTitleText {
            get {
                return ResourceManager.GetString("MenuPage_UpMenuTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织 的本地化字符串。
        /// </summary>
        public static string OrganizationPage_Title {
            get {
                return ResourceManager.GetString("OrganizationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string RolePage_ComfirmDeleteText {
            get {
                return ResourceManager.GetString("RolePage_ComfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新角色 的本地化字符串。
        /// </summary>
        public static string RolePage_CreateNewTitle {
            get {
                return ResourceManager.GetString("RolePage_CreateNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除该角色 的本地化字符串。
        /// </summary>
        public static string RolePage_DeleteTitle {
            get {
                return ResourceManager.GetString("RolePage_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑该角色 的本地化字符串。
        /// </summary>
        public static string RolePage_EditTitle {
            get {
                return ResourceManager.GetString("RolePage_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入名称 的本地化字符串。
        /// </summary>
        public static string RolePage_SearchKeywordPlaceholder {
            get {
                return ResourceManager.GetString("RolePage_SearchKeywordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置角色菜单 的本地化字符串。
        /// </summary>
        public static string RolePage_SetRoleMenuTitle {
            get {
                return ResourceManager.GetString("RolePage_SetRoleMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态修改成功！ 的本地化字符串。
        /// </summary>
        public static string RolePage_StatusChangedMessage {
            get {
                return ResourceManager.GetString("RolePage_StatusChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string RolePage_SubmitText {
            get {
                return ResourceManager.GetString("RolePage_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string RolePage_TableH1 {
            get {
                return ResourceManager.GetString("RolePage_TableH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string RolePage_TableH2 {
            get {
                return ResourceManager.GetString("RolePage_TableH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        public static string RolePage_TableH3 {
            get {
                return ResourceManager.GetString("RolePage_TableH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string RolePage_TableH4 {
            get {
                return ResourceManager.GetString("RolePage_TableH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string RolePage_Title {
            get {
                return ResourceManager.GetString("RolePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        public static string UserPage_ComfirmDeleteText {
            get {
                return ResourceManager.GetString("UserPage_ComfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新用户 的本地化字符串。
        /// </summary>
        public static string UserPage_CreateNewTitle {
            get {
                return ResourceManager.GetString("UserPage_CreateNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除该用户 的本地化字符串。
        /// </summary>
        public static string UserPage_DeleteTitle {
            get {
                return ResourceManager.GetString("UserPage_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户 的本地化字符串。
        /// </summary>
        public static string UserPage_EditTitle {
            get {
                return ResourceManager.GetString("UserPage_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户密码 的本地化字符串。
        /// </summary>
        public static string UserPage_ModifyPasswordTitle {
            get {
                return ResourceManager.GetString("UserPage_ModifyPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入关键字进行搜索 的本地化字符串。
        /// </summary>
        public static string UserPage_SearchKeywordPlaceholder {
            get {
                return ResourceManager.GetString("UserPage_SearchKeywordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string UserPage_SearchName {
            get {
                return ResourceManager.GetString("UserPage_SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择组织 的本地化字符串。
        /// </summary>
        public static string UserPage_SearchOrg {
            get {
                return ResourceManager.GetString("UserPage_SearchOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入姓名 的本地化字符串。
        /// </summary>
        public static string UserPage_SearchRealName {
            get {
                return ResourceManager.GetString("UserPage_SearchRealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择角色 的本地化字符串。
        /// </summary>
        public static string UserPage_SearchRole {
            get {
                return ResourceManager.GetString("UserPage_SearchRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置用户角色 的本地化字符串。
        /// </summary>
        public static string UserPage_SetUserRoleTitle {
            get {
                return ResourceManager.GetString("UserPage_SetUserRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态修改成功！ 的本地化字符串。
        /// </summary>
        public static string UserPage_StatusChangedMessage {
            get {
                return ResourceManager.GetString("UserPage_StatusChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string UserPage_SubmitText {
            get {
                return ResourceManager.GetString("UserPage_SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH1 {
            get {
                return ResourceManager.GetString("UserPage_TableH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH2 {
            get {
                return ResourceManager.GetString("UserPage_TableH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH3 {
            get {
                return ResourceManager.GetString("UserPage_TableH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH4 {
            get {
                return ResourceManager.GetString("UserPage_TableH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH5 {
            get {
                return ResourceManager.GetString("UserPage_TableH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH6 {
            get {
                return ResourceManager.GetString("UserPage_TableH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH7 {
            get {
                return ResourceManager.GetString("UserPage_TableH7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织 的本地化字符串。
        /// </summary>
        public static string UserPage_TableH8 {
            get {
                return ResourceManager.GetString("UserPage_TableH8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string UserPage_Title {
            get {
                return ResourceManager.GetString("UserPage_Title", resourceCulture);
            }
        }
    }
}
