//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAdmin.Layout.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayoutCulture {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutCulture() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorAdmin.Layout.Resources.LayoutCulture", typeof(LayoutCulture).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string CultureLanguage {
            get {
                return ResourceManager.GetString("CultureLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑暗 的本地化字符串。
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑暗模式 的本地化字符串。
        /// </summary>
        internal static string ThemeDarkMode {
            get {
                return ResourceManager.GetString("ThemeDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明亮 的本地化字符串。
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色 的本地化字符串。
        /// </summary>
        internal static string ThemePrimary {
            get {
                return ResourceManager.GetString("ThemePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string 关于 {
            get {
                return ResourceManager.GetString("关于", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审计 的本地化字符串。
        /// </summary>
        internal static string 审计 {
            get {
                return ResourceManager.GetString("审计", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string 日志 {
            get {
                return ResourceManager.GetString("日志", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string 权限 {
            get {
                return ResourceManager.GetString("权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string 用户 {
            get {
                return ResourceManager.GetString("用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string 登录 {
            get {
                return ResourceManager.GetString("登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string 系统 {
            get {
                return ResourceManager.GetString("系统", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织 的本地化字符串。
        /// </summary>
        internal static string 组织 {
            get {
                return ResourceManager.GetString("组织", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        internal static string 菜单 {
            get {
                return ResourceManager.GetString("菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string 角色 {
            get {
                return ResourceManager.GetString("角色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string 配置 {
            get {
                return ResourceManager.GetString("配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string 首页 {
            get {
                return ResourceManager.GetString("首页", resourceCulture);
            }
        }
    }
}
