//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAdmin.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CusCulture {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CusCulture() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorAdmin.Core.Resources.CusCulture", typeof(CusCulture).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string AuditLogDetailDialog_TableH1 {
            get {
                return ResourceManager.GetString("AuditLogDetailDialog_TableH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名 的本地化字符串。
        /// </summary>
        public static string AuditLogDetailDialog_TableH2 {
            get {
                return ResourceManager.GetString("AuditLogDetailDialog_TableH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧值 的本地化字符串。
        /// </summary>
        public static string AuditLogDetailDialog_TableH3 {
            get {
                return ResourceManager.GetString("AuditLogDetailDialog_TableH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新值 的本地化字符串。
        /// </summary>
        public static string AuditLogDetailDialog_TableH4 {
            get {
                return ResourceManager.GetString("AuditLogDetailDialog_TableH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_OperationCreate {
            get {
                return ResourceManager.GetString("AuditLogPage_OperationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_OperationDelete {
            get {
                return ResourceManager.GetString("AuditLogPage_OperationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_OperationModify {
            get {
                return ResourceManager.GetString("AuditLogPage_OperationModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH1 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事务id 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH2 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH3 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作对象 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH4 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH5 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH6 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值记录 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_TableH7 {
            get {
                return ResourceManager.GetString("AuditLogPage_TableH7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审计日志 的本地化字符串。
        /// </summary>
        public static string AuditLogPage_Title {
            get {
                return ResourceManager.GetString("AuditLogPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主颜色选择 的本地化字符串。
        /// </summary>
        public static string AuthorizedLayout_ColorPickerTitle {
            get {
                return ResourceManager.GetString("AuthorizedLayout_ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string AuthorizedLayout_Language {
            get {
                return ResourceManager.GetString("AuthorizedLayout_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English(United State) 的本地化字符串。
        /// </summary>
        public static string AuthorizedLayout_Language_enus {
            get {
                return ResourceManager.GetString("AuthorizedLayout_Language_enus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string AuthorizedLayout_Language_zhcn {
            get {
                return ResourceManager.GetString("AuthorizedLayout_Language_zhcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string AuthorizedLayout_Logout {
            get {
                return ResourceManager.GetString("AuthorizedLayout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号信息 的本地化字符串。
        /// </summary>
        public static string AuthorizedLayout_Setting {
            get {
                return ResourceManager.GetString("AuthorizedLayout_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回首页 的本地化字符串。
        /// </summary>
        public static string BackToHome_Text {
            get {
                return ResourceManager.GetString("BackToHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了一个系统错误！ 的本地化字符串。
        /// </summary>
        public static string Error_Text {
            get {
                return ResourceManager.GetString("Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login_LoginText {
            get {
                return ResourceManager.GetString("Login_LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string Login_PasswordHelpText {
            get {
                return ResourceManager.GetString("Login_PasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Login_UserNameHelpText {
            get {
                return ResourceManager.GetString("Login_UserNameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_LoginFail {
            get {
                return ResourceManager.GetString("LoginLogPage_LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_LoginSuccess {
            get {
                return ResourceManager.GetString("LoginLogPage_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_TableH1 {
            get {
                return ResourceManager.GetString("LoginLogPage_TableH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_TableH2 {
            get {
                return ResourceManager.GetString("LoginLogPage_TableH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录时间 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_TableH3 {
            get {
                return ResourceManager.GetString("LoginLogPage_TableH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录IP 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_TableH4 {
            get {
                return ResourceManager.GetString("LoginLogPage_TableH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否成功 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_TableH5 {
            get {
                return ResourceManager.GetString("LoginLogPage_TableH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录客户端 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_TableH6 {
            get {
                return ResourceManager.GetString("LoginLogPage_TableH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录日志 的本地化字符串。
        /// </summary>
        public static string LoginLogPage_Title {
            get {
                return ResourceManager.GetString("LoginLogPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换其他用户 的本地化字符串。
        /// </summary>
        public static string NoAuhtorized_ChangeUserText {
            get {
                return ResourceManager.GetString("NoAuhtorized_ChangeUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有访问该页面的权限... 的本地化字符串。
        /// </summary>
        public static string NoAuhtorized_Text {
            get {
                return ResourceManager.GetString("NoAuhtorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，没有找到这个地址 的本地化字符串。
        /// </summary>
        public static string NotFound_Text {
            get {
                return ResourceManager.GetString("NotFound_Text", resourceCulture);
            }
        }
    }
}
